version: '3.3'

services: 
  app:
    hostname: app-host
    restart: always
    image: mrbacky/frontend-calc
  hub: 
    hostname: hub-host
    restart: always
    image: selenium/hub
    depends_on: 
      - app
    ports: 
      - "4444:4444"

  firefox-node:
    restart: always
    image: selenium/node-firefox
    depends_on: 
      - hub
    environment: 
      HUB_HOST: hub-host
  
  chrome-node:
    restart: always
    image: selenium/node_chrome
    depends_on: 
      - hub
    environment:
      HUB_HOST: hub-host
