version: "3.3"

services:
  backend:
    hostname: backend-host-5
    restart: always
    image: mrbacky/backend-calc
  app:
    hostname: app-host-5
    restart: always
    image: mrbacky/frontend-calc
    depends_on:
      - backend
  hub:
    hostname: hub-host-5
    restart: always
    image: selenium/hub
    depends_on:
      - app
    ports:
      - "4444:4444"
  firefox-node:
    restart: always
    image: selenium/node-firefox
    depends_on:
      - hub
    environment:
      HUB_HOST: hub-host-5
  chrome-node:
    restart: always
    image: selenium/node-chrome
    depends_on:
      - hub
    environment:
      HUB_HOST: hub-host-5
